% Simulink CAN Bus IDS Configuration
% Add this to your Simulink model initialization

% TCP/IP Configuration for Python IDS
IDS_HOST = 'localhost';
IDS_PORT = 8888;

% CAN Message Parameters
CAN_IDS = struct(...
    'SPEED', hex2dec('100'), ...
    'RPM', hex2dec('101'), ...
    'BRAKE', hex2dec('102'), ...
    'STEERING', hex2dec('103'), ...
    'ENGINE_TEMP', hex2dec('104'), ...
    'FUEL_LEVEL', hex2dec('105') ...
);

% Attack Simulation Parameters
ATTACK_PARAMS = struct(...
    'DOS_RATE', 100, ...
    'FUZZING_PROB', 0.1, ...
    'SPOOFING_VALUES', [250, 10000, 150] ...
);

% Sample Time
Ts = 0.01; % 10ms sample time

fprintf('✅ Simulink CAN IDS Configuration Loaded\n');